name: Playwright Accessibility Tests
on:
    # allow for manual triggers
    workflow_dispatch: {}
    push:
        branches: [playwright-automated-testing]
    pull_request:
        branches: [playwright-automated-testing]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        strategy:
            matrix:
                countries: [AU, DE, GB, FR, IT, ES, US]

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm i
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run server
              run: |
                  ./.github/scripts/runServerV2.sh
            - name: Run Playwright Modals
              continue-on-error: true
              run: npx playwright test tests/playwright/tests/sdk/modals --grep @${{matrix.countries}} --output=playwright-report-${{matrix.countries}}
            - name: Run Playwright Messages
              continue-on-error: true
              run: npx playwright test tests/playwright/tests/sdk/messages --grep @${{matrix.countries}} --output=playwright-report-${{matrix.countries}}
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report-${{matrix.countries}}
                  path: playwright-report/
                  retention-days: 30
