name: Update Snapshots - Non-US
on:
    # allow for manual triggers
    workflow_dispatch: {}
    pull_request: {}
    pull_request_target:
        types: [labeled]

jobs:
    getLocales:
        name: Get Locales
        if: contains(github.event.pull_request.labels.*.name, 'snapshots')
        runs-on: ubuntu-latest
        outputs:
            locale: ${{ steps.setMatrix.outputs.locale }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - id: setMatrix
              run: echo "::set-output name=locale::$(cat ./.github/locales.json | tr '\n' ' ')"

    updateSnapshots:
        name: Non-US
        if: contains(github.event.pull_request.labels.*.name, 'snapshots')
        runs-on: ubuntu-latest
        needs: getLocales
        strategy:
            matrix:
                locale: ${{ fromJSON(needs.getLocales.outputs.locale) }}
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: ðŸ“¥ Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: |
                  ./.github/scripts/runServer.sh

            - name: Update Banner Snapshots - ${{ matrix.locale }}
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/${{ matrix.locale }}/banner
                  git status

            - name: Update Modal Snapshots - ${{ matrix.locale }}
              run: |
                  npm run test:func:ciupdate -- --testPathPattern spec/${{ matrix.locale }}/modal
                  git status

            - name: Commit Updated Snapshots - ${{ matrix.locale }}
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'chore(snapshots): update ${{ matrix.locale }} snapshots [skip ci]'
                  commit_options: '--no-verify --quiet'
                  commit_user_name: Snapshot Actions Bot
                  file_pattern: tests/functional/snapshots/
                  push_options: '-v'
